
#  _  __          _____  _    _ _    _ 
# | |/ /    /   |  __ | |  | | |  | |
# | ' /    /    | |__) | |__| | |  | |
# |  <    / /  |  _  /|  __  | |  | |
# | .   / ____ | |  | |  | | |__| |
# |_|_/_/    __|  __|  |_|____/ 
#♡ Thanks for purchasing Karhu anti-cheat                       
#Website: https://www.karhu.cc
#Discord: https://www.karhu.cc/discord
#     
#     
#Start by adding your license key here!   
#You can get your license from your email
#It should look like this: 51D43-7CABC-E8F60-21982-6FFFF
#ShoppyID / OrderID IS NOT your license!
license-key: PURCHASE-KARHU-TO-GET-KEY
version-to-download: 2.2-beta
Prefix: '&7[&b&l❀&7] '
MiscPrefix: '&7[&e⚠&7] '
experimental-alert-symbol: '&aΔ'
AlertsMessage: '&f%player% &7failed &b%check% &7[x&b%vl%&7]'
ClientCheckMessage: '&f%player% &7joined using &7[&e%brand%&7]'
AntiCrashMessage: '&e%player% &fwas kicked for &esuspicious activity &7(&e%debug%&7)'
NetHandlerMessage: '&e%player% &fwas kicked for &esuspicious network activity &7(&6%debug%&7)'
VehicleHandlerMessage: '&f%player% &7sent a vehicle packet in an invalid state'
AlertsHoverableMessage: |-
    &f%info%
    (Ping: %ping% TPS: %tps%) &a(Click to teleport)
AlertsHoverableMessageHighlightColor: '&b'
GuiHighlightColor: '&l&b'
AlertsClickCommand:
    command: /tp %player%
spigot-api-alert: true
hoverless-alert: false
alert-delay: 50
Punishments:
    broadcast: true
    message: |-
        &7&m--------------------------------------------------
        &c&l✗ &b&lKARHU CHEAT DETECTION
        &fKarhu &7has removed a player from the network due to cheating
        &7&m--------------------------------------------------
    banCommand:
        - ban %player% Hacked client
    kickCommand:
        - kick %player% Hacked client
    command-delay-seconds: 0
PunishCommand:
    - ban %player% Hacked client
server-name: Karhu
autoban: false
bungee:
    execute-ban-command-in-bungee: false
    alerts: false
    alert-post-vl-rate: 10
anticrash:
    enabled: true
    move-spam: true
    place-spam: true
    large-move: true
    window-spam: true
    payload-spam: true
    slot-spam: true
    arm-spam: true
    kick-message: 'java.net.IOException Connection timed out: no further information'
nethandler:
    enabled: true
    spoof: true
    delay: true
    kick-message: 'java.net.IOException Connection timed out: no further information'
    transaction-order:
        '&c%player% &7ignored order of transactions &7first was &a%first%
        &7sent §c%sent%'
    cancel-keepalives-alert:
        '&c%player% &7cancelled keepalive packets with total of
        &a%invalid% / %total%'
    cancel-transactions-alert:
        '&c%player% &7cancelled transaction packets with total
        of &a%invalid% / %total%'
    own-keepalives-alert:
        '&c%player% &7sent own keepalives &7total of &a%invalid% /
        %total%'
    own-transactions-alert:
        '&c%player% &7sent own transactions &7total of &a%invalid%
        / %total%'
    cancel-and-own-kick-message:
        'java.net.IOException Connection timed out: no further
        information'
    wrong-order-kick-message: Timed out (%first% != %received%)
vehicle-handler:
    unmount: false
unallowed-brands:
    brands: |-
        Vivecraft
        Crystalware
    kick-msg: This client is unallowed on our server!
pullback:
    enabled: true
    type: generic
client-check: true
bypass-permission: false
anticheat-name: Karhu
anti-vpn:
    enabled: true
    proxy-check: true
    malicious-check: true
    bypass:
        - UUID1
        - UUID2
    kick-message: |-
        &3&l✧ &b&lKarhu &3&l✧

        &cUsage of VPN is prohibited!
discord:
    enabled: false
    alert-webhook-url: INSERT_HERE
    crash-webhook-url: INSERT_HERE
    show-world: true
    show-statistics: true
    show-icon-thumbnail: true
    post-vl-rate: 10
    send-alerts: true
    send-bans: true
high-ping-kick:
    enabled: false
    max-ping: 1000
    ping-over-max-ticks-before-kick: 250
    kick-message: Your ping constantly too high, do something
packetevents:
    injectAsync: true
    ejectAsync: true
    injectEarly: true
    kickUninjected: true
    uninjected-kick-message: "&cWe've failed to load your data, please reconnect!"
commands:
    alerts:
        enabled: '&b&lKARHU &7// &aAlerts on!'
        disabled: '&b&lKARHU &7// &cAlerts off!'
    help: |-
        &3&l> &b&lKarhu &3&l<

        &b* &7/karhu alerts - check alerts
        &b* &7/karhu GUI - use GUI
        &b* &7/karhu logs - check logs from database
        &b* &7/karhu pastelogs - paste all logs to hastebin
        &b* &7/karhu recentbans - view recentbans
        &b* &7/karhu manualban - ban cheater manually
        &b* &7/karhu stats - view server Timings
        &b* &7/karhu sessionlogs - check logs that havent expired yet in the vl system
        &b* &7/karhu info <player> - see info about player
        &b* &7/karhu version - check Karhu version
        &b* &7/karhu reload - reload config
    banwave: |-
        &3&l> &b&lKarhu &3&l<

        &b* &7/karhu banwave gui - open management gui
        &b* &7/karhu banwave list - see players that will be banned
    logs:
        ban-color: '&c'
        highlight-color: '&b'
    no-permission: "&cYou don''t have required permissions!"
default-version: '1_8'
database: FlatFile
mysql:
    user: karhu
    address: localhost
    password: password
    database: karhu
    port: 3306
mongo:
    host: 127.0.0.1
    port: 27017
    database: karhu
    authentication:
        enabled: false
        username: karhu
        password: password
noautoban-alert-symbol: '&c≠'
reset-violations-on-leave: true
disallow-flags-after-punishment: true
cracked-server: false
geyser:
    stop-injecting-bedrock-players: true
ghostblock-support:
    enabled: true
    lagback-on-walk: true
    update-on-walk: true
    liquid-dector: true
server-lag-protection:
    max-tick-length: 110
    warning-message:
        "%prefix% &c%player% &fwould've flagged, but server lagged within
        &c1 second&f."
    warning-display-type: CONSOLE
async-kb-fix: false
join-exempt-ticks: 100
banwaves:
    punish: configurethis %player%
    messages:
        caught: '&b%player% &3has been caught in the &bBan Wave!'
        complete:
            '&bKarhu &3has finished the banwave. A total of &b%bans% players &3were
            banned.'
    broadcast-caught: true
    broadcast-complete: true
